### PR TITLE
test(e2e): allow e2e-agent to control devices

### PR DESCRIPTION
**Pull request by chriswldenyer**
allow e2e-agent to set a backing device to offline or running

### CODE REVIEW

**Review by blaisedias — APPROVED** [review]

**Review by payes — APPROVED** [review]

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
Superseded by PR#366

**Pull request closed without merging**
