### PR TITLE
chore: add another build parameter to specify number of times tests should run in custom pipeline

### PR DESCRIPTION
**Pull request by rohan2794**
JIRA: https://mayadata.atlassian.net/browse/MQ-2549

### CODE REVIEW

**Review by blaisedias — APPROVED** [review]
LGTM
Would the next step  be the ability run `install, mytest * N times, uninstall`?

**Review by blaisedias — CHANGES_REQUESTED** [review]
Oh just realised this will not work with multiple install...,uninstall because e2e-test.sh treats uninstall as a special case.
What is needed is
`install test test test test ...... uninstall`

**Comment by rohan2794** [comment]
> Oh just realised this will not work with multiple install...,uninstall because e2e-test.sh treats uninstall as a special case. What is needed is `install,test,test,test,test,......,uninstall`

Done

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Review by blaisedias — APPROVED** [review]

**Pull request merged**
