### PR TITLE
chore: refactor use of GetMsPool and ListMsPools function with MOAC and kubectl plugin

### PR DESCRIPTION
**Pull request by rohan2794**
Add abstraction for GetMsPool and ListMsPools function . Removed explicit call to pool CRDs .
Updated the test to use k8stest.ListMsPools and k8stest.GetMsPool function.

JIRA: https://mayadata.atlassian.net/browse/MQ-2500

### CODE REVIEW

**Comment by rohan2794** [comment]
bors try

**Review by blaisedias — APPROVED** [review]

**Review by blaisedias — APPROVED** [review]

**Review by payes — APPROVED** [review]

**Comment by rohan2794** [comment]
bors merge

**Comment by rohan2794** [comment]
bors merge

**Comment by rohan2794** [comment]
bors merge

**Pull request merged**
