### PR TITLE
refactor: move tests sources files to src/tests

### PR DESCRIPTION
**Pull request by blaisedias**
Migration done using goland
Manual fixes:
Fix e2e-test.sh to work with new location.

### CODE REVIEW

**Comment by blaisedias** [comment]
bors try

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Review by rohan2794 — APPROVED** [review]

**Comment by blaisedias** [comment]
bors merge

**Comment by blaisedias** [comment]
bors merge

**Pull request merged**
