### PR TITLE
chore: add node selector to fio pod definition

### PR DESCRIPTION
**Pull request by rohan2794**
JIRA: https://mayadata.atlassian.net/browse/MQ-2509

### CODE REVIEW

**Review by chriswldenyer — APPROVED** [review]
LGTM. Could you put the reason for the change in the description?

**Review by blaisedias — COMMENTED** [review]
This change is in the shared code, so implications are wide ranging.
If the fix is for a test then for now can we localise the change to that test.
`CreateFioPodDef` is deprecated, so maybe the fix is to use the builder pattern?

**Comment by rohan2794** [comment]
> This change is in the shared code, so implications are wide ranging. If the fix is for a test then for now can we localise the change to that test. `CreateFioPodDef` is deprecated, so maybe the fix is to use the builder pattern?

Couple of tests where mayastor node is suppressed are affected due to this changes are not localise.
IMHO deprecated can be removed under new task, now just doing small fixes in existing code.

**Review by blaisedias — APPROVED** [review]
LGTM

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Comment by rohan2794** [comment]
bors merge

**Pull request merged**
